### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [qnopka/kinozal#1]
1)
и в бутстрапе, и по смыслу - неправильная структура.
во втором блоке, аналогично, и на другой странице тоже.
![image](https://user-images.githubusercontent.com/8464662/96359091-366d8800-1117-11eb-90c6-a175f1d5fcb4.png)

2)
невалидный стиль
![image](https://user-images.githubusercontent.com/8464662/96359100-5dc45500-1117-11eb-9f98-d075be15c748.png)

3)
скругления отсутствуют
![image](https://user-images.githubusercontent.com/8464662/96359103-70d72500-1117-11eb-95a5-b8539a68e858.png)

4)
активный класс надо смещать
![image](https://user-images.githubusercontent.com/8464662/96359115-99f7b580-1117-11eb-9c8a-fa999126f9a6.png)

**Comment by qnopka** [comment]
https://github.com/qnopka/kinozal
https://qnopka.github.io/kinozal/page.html

Попович Екатерина, сб/вс 12-00-14:00

**Comment by Alecto** [comment]
заголовок решили не исправлять?

хорошо.
работа принята.

нд, 18 жовт. 2020 о 10:09 qnopka <notifications@github.com> пише:
